FROM python:3.11-slim

WORKDIR /app
COPY analytics-python/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY analytics-python ./

ENV REDIS_URL=redis://redis:6379
CMD ["python", "main.py"]
